In [1]:
import numpy as np

In [2]:
data = np.array([1, 1, 0, 0, 0])

In [3]:
2**data

array([2, 2, 1, 1, 1])

In [4]:
data = np.array([1, 1, 0, 0, 0])
p = np.linspace(0, 1, 11)
bernoulli = (p**data)*((1-p)**(1-data))

ValueError: operands could not be broadcast together with shapes (11,) (5,) 

In [ ]:
np.linspace(0, 1, 11)

In [ ]:
data = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])  # Data (Bernoulli outcomes)
p = np.linspace(0, 1, 11)  # Probability values (0 to 1)
# Reshape p and data for broadcasting
p = p[:, np.newaxis]  # Make p a column vector
data = data[np.newaxis, :]  # Make data a row vector
bernoulli = (p**data) * ((1 - p) ** (1 - data))
np.prod(bernoulli, axis=1)

In [5]:
1/5

0.2

In [6]:
2/5

0.4

In [7]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

breast_cancer = load_breast_cancer(as_frame=True)

In [8]:
df_breast_cancer = breast_cancer.data
df_breast_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [9]:
arr_target = np.array(breast_cancer.target.copy())
arr_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
arr_mean_radius = np.array(df_breast_cancer["mean radius"].copy())
arr_mean_radius

array([17.99 , 20.57 , 19.69 , 11.42 , 20.29 , 12.45 , 18.25 , 13.71 ,
       13.   , 12.46 , 16.02 , 15.78 , 19.17 , 15.85 , 13.73 , 14.54 ,
       14.68 , 16.13 , 19.81 , 13.54 , 13.08 ,  9.504, 15.34 , 21.16 ,
       16.65 , 17.14 , 14.58 , 18.61 , 15.3  , 17.57 , 18.63 , 11.84 ,
       17.02 , 19.27 , 16.13 , 16.74 , 14.25 , 13.03 , 14.99 , 13.48 ,
       13.44 , 10.95 , 19.07 , 13.28 , 13.17 , 18.65 ,  8.196, 13.17 ,
       12.05 , 13.49 , 11.76 , 13.64 , 11.94 , 18.22 , 15.1  , 11.52 ,
       19.21 , 14.71 , 13.05 ,  8.618, 10.17 ,  8.598, 14.25 ,  9.173,
       12.68 , 14.78 ,  9.465, 11.31 ,  9.029, 12.78 , 18.94 ,  8.888,
       17.2  , 13.8  , 12.31 , 16.07 , 13.53 , 18.05 , 20.18 , 12.86 ,
       11.45 , 13.34 , 25.22 , 19.1  , 12.   , 18.46 , 14.48 , 19.02 ,
       12.36 , 14.64 , 14.62 , 15.37 , 13.27 , 13.45 , 15.06 , 20.26 ,
       12.18 ,  9.787, 11.6  , 14.42 , 13.61 ,  6.981, 12.18 ,  9.876,
       10.49 , 13.11 , 11.64 , 12.36 , 22.27 , 11.34 ,  9.777, 12.63 ,
      

In [11]:
arr_features = np.array(df_breast_cancer.copy())
arr_features.shape

(569, 30)

In [12]:
arr_mean_radius_sort = np.sort(arr_mean_radius)
arr_mean_radius_sort

array([ 6.981,  7.691,  7.729,  7.76 ,  8.196,  8.219,  8.571,  8.597,
        8.598,  8.618,  8.671,  8.726,  8.734,  8.878,  8.888,  8.95 ,
        9.   ,  9.029,  9.042,  9.173,  9.268,  9.295,  9.333,  9.397,
        9.405,  9.423,  9.436,  9.465,  9.504,  9.567,  9.606,  9.667,
        9.668,  9.676,  9.683,  9.72 ,  9.731,  9.738,  9.742,  9.742,
        9.755,  9.777,  9.787,  9.847,  9.876,  9.876,  9.904, 10.03 ,
       10.05 , 10.08 , 10.16 , 10.17 , 10.18 , 10.2  , 10.25 , 10.26 ,
       10.26 , 10.26 , 10.29 , 10.32 , 10.44 , 10.48 , 10.48 , 10.49 ,
       10.49 , 10.51 , 10.51 , 10.57 , 10.57 , 10.6  , 10.65 , 10.66 ,
       10.71 , 10.75 , 10.8  , 10.8  , 10.82 , 10.86 , 10.88 , 10.9  ,
       10.91 , 10.94 , 10.95 , 10.96 , 10.97 , 11.04 , 11.04 , 11.06 ,
       11.06 , 11.06 , 11.08 , 11.08 , 11.13 , 11.13 , 11.14 , 11.15 ,
       11.16 , 11.2  , 11.22 , 11.22 , 11.25 , 11.26 , 11.26 , 11.27 ,
       11.27 , 11.28 , 11.29 , 11.3  , 11.31 , 11.32 , 11.33 , 11.34 ,
      

In [13]:
arr_mean_radius_sort[]

SyntaxError: invalid syntax (3754551428.py, line 1)

In [14]:
arr_test = np.array([1,2,3])
beg_arr_test = arr_test[0:-1]
end_arr_test = arr_test[1:]

In [15]:
(beg_arr_test+end_arr_test)/2

array([1.5, 2.5])

In [16]:
def thresholds(arr):
    arr_sorted = np.sort(np.unique(arr))
    beginning_arr = arr_sorted[0:-1]
    end_arr = arr_sorted[1:]
    return (beginning_arr + end_arr) / 2

In [17]:
thresholds(arr_mean_radius_sort)

array([ 7.336 ,  7.71  ,  7.7445,  7.978 ,  8.2075,  8.395 ,  8.584 ,
        8.5975,  8.608 ,  8.6445,  8.6985,  8.73  ,  8.806 ,  8.883 ,
        8.919 ,  8.975 ,  9.0145,  9.0355,  9.1075,  9.2205,  9.2815,
        9.314 ,  9.365 ,  9.401 ,  9.414 ,  9.4295,  9.4505,  9.4845,
        9.5355,  9.5865,  9.6365,  9.6675,  9.672 ,  9.6795,  9.7015,
        9.7255,  9.7345,  9.74  ,  9.7485,  9.766 ,  9.782 ,  9.817 ,
        9.8615,  9.89  ,  9.967 , 10.04  , 10.065 , 10.12  , 10.165 ,
       10.175 , 10.19  , 10.225 , 10.255 , 10.275 , 10.305 , 10.38  ,
       10.46  , 10.485 , 10.5   , 10.54  , 10.585 , 10.625 , 10.655 ,
       10.685 , 10.73  , 10.775 , 10.81  , 10.84  , 10.87  , 10.89  ,
       10.905 , 10.925 , 10.945 , 10.955 , 10.965 , 11.005 , 11.05  ,
       11.07  , 11.105 , 11.135 , 11.145 , 11.155 , 11.18  , 11.21  ,
       11.235 , 11.255 , 11.265 , 11.275 , 11.285 , 11.295 , 11.305 ,
       11.315 , 11.325 , 11.335 , 11.35  , 11.365 , 11.39  , 11.415 ,
       11.425 , 11.4

In [18]:
def thresholds_with_loop(arr):
    arr_sorted = np.sort(np.unique(arr))
    thresholds = []
    for i in range(len(arr_sorted) - 1):
        thresholds.append((arr_sorted[i] + arr_sorted[i + 1]) / 2)
    return np.array(thresholds)

In [19]:
%%time
thresholds_with_loop(arr_mean_radius_sort)

CPU times: user 1.56 ms, sys: 811 µs, total: 2.37 ms
Wall time: 1.56 ms


array([ 7.336 ,  7.71  ,  7.7445,  7.978 ,  8.2075,  8.395 ,  8.584 ,
        8.5975,  8.608 ,  8.6445,  8.6985,  8.73  ,  8.806 ,  8.883 ,
        8.919 ,  8.975 ,  9.0145,  9.0355,  9.1075,  9.2205,  9.2815,
        9.314 ,  9.365 ,  9.401 ,  9.414 ,  9.4295,  9.4505,  9.4845,
        9.5355,  9.5865,  9.6365,  9.6675,  9.672 ,  9.6795,  9.7015,
        9.7255,  9.7345,  9.74  ,  9.7485,  9.766 ,  9.782 ,  9.817 ,
        9.8615,  9.89  ,  9.967 , 10.04  , 10.065 , 10.12  , 10.165 ,
       10.175 , 10.19  , 10.225 , 10.255 , 10.275 , 10.305 , 10.38  ,
       10.46  , 10.485 , 10.5   , 10.54  , 10.585 , 10.625 , 10.655 ,
       10.685 , 10.73  , 10.775 , 10.81  , 10.84  , 10.87  , 10.89  ,
       10.905 , 10.925 , 10.945 , 10.955 , 10.965 , 11.005 , 11.05  ,
       11.07  , 11.105 , 11.135 , 11.145 , 11.155 , 11.18  , 11.21  ,
       11.235 , 11.255 , 11.265 , 11.275 , 11.285 , 11.295 , 11.305 ,
       11.315 , 11.325 , 11.335 , 11.35  , 11.365 , 11.39  , 11.415 ,
       11.425 , 11.4

In [20]:
%%time
test = thresholds(arr_mean_radius_sort)

CPU times: user 652 µs, sys: 175 µs, total: 827 µs
Wall time: 704 µs


In [21]:
# np.where(arr_mean_radius_sort > test[0])
len(arr_target[arr_mean_radius > test[1]])

567

In [143]:
len(arr_target)

569

In [134]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
def create_tree_split(feature_arr, ) 
mask_left = feature_arrays[:, feature_best] > feature_threshold_best
mask_right = feature_arrays[:, feature_best] < feature_threshold_best
left_features = feature_arrays[mask_left]
right_features = feature_arrays[mask_right]
left_target = target_arr[mask_left]
right_target = target_arr[mask_right]

ValueError: either both or neither of x and y should be given

In [22]:
import math
import itertools

def thresholds(arr):
    arr_sorted = np.sort(np.unique(arr))
    beginning_arr = arr_sorted[0:-1]
    end_arr = arr_sorted[1:]
    return (beginning_arr + end_arr) / 2

def weights(parent_array, child_array):
    """
    This function calculates the weights for the child arrays.
    """
    return len(child_array) / len(parent_array)

def entropy(arr):
    """
    This function calculates entropy for the target class data passed to the function.
    """
    p = sum(arr)/len(arr)
    if p == 0 or p == 1:
        return 0  # Directly return 0 for certainty
    return -p*math.log2(p) - (1-p)*math.log2(1-p)

def information_gain(parent_entropy, 
                     weighted_entropy):
    """
    This function calculates information gain.
    """
    return parent_entropy - weighted_entropy

def weighted_entropy(child_entropies: list, 
                     child_weights: list):
    """ 
    This function calculates the weighted entropy.
    """
    child_entropy_1 = child_entropies[0]
    child_entropy_2 = child_entropies[1]
    child_weight_1 = child_weights[0]
    child_weight_2 = child_weights[1]

    return child_weight_1 * child_entropy_1 + child_weight_2 * child_entropy_2


def find_best_split(feature_arrays, target_arr):
    """ 
    This code identifies the best feature split.
    """
    weighted_entropy_best = 10000000
    feature_best = 0
    feature_threshold_best = 0
    num_features = arr_features.shape[1]

    for feature_ind in range(num_features):
        feature_arr = feature_arrays[:, feature_ind]
        feature_thresholds = thresholds(feature_arr)

        for threshold_ind in range(len(feature_thresholds)):

            child_arr_1 = target_arr[feature_arr > feature_thresholds[threshold_ind]]
            child_arr_2 = target_arr[feature_arr < feature_thresholds[threshold_ind]]

            child_entropy_1 = entropy(child_arr_1)
            child_entropy_2 = entropy(child_arr_2)

            child_weight_1 = weights(target_arr, child_arr_1)
            child_weight_2 = 1 - child_weight_1

            weighted_entropy_current = weighted_entropy(
                [child_entropy_1, child_entropy_2],
                [child_weight_1, child_weight_2],
            )

            if weighted_entropy_current<weighted_entropy_best:
                weighted_entropy_best = weighted_entropy_current
                feature_threshold_best = feature_thresholds[threshold_ind]
                feature_best = feature_ind

    return weighted_entropy_best, feature_threshold_best, feature_best

def create_leaf(leaf_node,
                feature = None, 
                threshold = None, 
                class_value = None):
    """ 
    
    """
    if leaf_node == 0:
        leaf_dictionary = {'leaf_node': 'node',
                           'feature': feature,
                           'threshold': threshold,
                           'left':None,
                           'right':None }
    elif leaf_node == 1:
        leaf_dictionary = {'leaf_node': 'leaf', "class": class_value}

    return leaf_dictionary


def generate_unique_combinations_matrix(rows):
    """
    Generate a matrix with unique combinations of 0s and 1s for each column.

    Parameters:
    rows (int): Number of rows in the matrix.

    Returns:
    np.ndarray: A binary matrix of shape (rows, 2^rows) with unique column combinations.
    """
    # Generate all possible unique combinations for the given number of rows
    all_combinations = np.array(list(itertools.product([0, 1], repeat=rows)))
    return all_combinations.T  # Transpose so that columns represent unique combinations


def build_tree(feature_arrays, target_arr, max_depth = 10):
    """ 
    # add function to travel down branches for loop and return variables to split the data
    # split feature and target data, find the best split, create leaf
    """

    # level 0 branch creation
    weighted_entropy_best, feature_threshold_best, feature_best = find_best_split(
        feature_arrays, target_arr
    )

    tree = create_leaf(
        leaf_node=0,
        feature=feature_best, 
        threshold = feature_threshold_best
    )
    # create function from here
    mask_left = feature_arrays[:, feature_best] > feature_threshold_best
    mask_right = feature_arrays[:, feature_best] < feature_threshold_best
    left_features = feature_arrays[mask_left]
    right_features = feature_arrays[mask_right]
    left_target = target_arr[mask_left]
    right_target = target_arr[mask_right]

    left_weighted_entropy_best, left_feature_threshold_best, left_feature_best = find_best_split(
        left_features, left_target
    )

    right_weighted_entropy_best, right_feature_threshold_best, right_feature_best = (
        find_best_split(right_features, right_target)
    )

    tree["left"] = create_leaf(
        leaf_node=0, feature=left_feature_best, threshold=left_feature_threshold_best
    )

    tree["right"] = create_leaf(
        leaf_node=0, feature=right_feature_best, threshold=right_feature_threshold_best
    )
    
    # parent_entropy = entropy(target_arr)
    # child_entropy = weighted_entropy_best
    # depth = 0
    # directions = ["left", "right"]
    # while depth < max_depth:
    #     depth += 1
    #     num_branches = 2**depth
    #     branch_routes = generate_unique_combinations_matrix(rows=depth)
    #     leaf = tree

    #     for branch in range(num_branches):
    #         for direction in branch_routes[:, branch]:
    #             leaf = leaf[branch[directions[direction]]]
    #             if leaf == None: # if class == 1,0? 
    #                 break
    #             feature = leaf["feature"]
    #             threshold = leaf["threshold"]

                # split features and target
                # find best split
                # create tree with left and right node
                # break out of while loop when no more branching can occur i.e. no more leaf nodes

    return tree

In [23]:
%%time
matrix_test = generate_unique_combinations_matrix(20)
matrix_test.shape

CPU times: user 1.75 s, sys: 97.4 ms, total: 1.85 s
Wall time: 1.85 s


(20, 1048576)

In [17]:
branches = generate_unique_combinations_matrix(tree_depth)

tree = None
if tree == None:
    tree = {}
    # level 0 branch creation
    weighted_entropy_best, feature_threshold_best, feature_best = find_best_split(
        feature_arrays, target_arr
    )

    tree = create_leaf(
        leaf_node=0,
        feature=feature_best, 
        threshold = feature_threshold_best
    )
else:
    print('bye')
    for route in range(len(branches[0, :])):
        tree_copy = tree
        epoch = 0
        for branch in branches[:, route]:
            epoch +=1
            direction = ["left", "right"][branch]
            if epoch < tree_depth:
                tree_copy = tree_copy[direction]
                print(epoch,' : ' , tree_copy)
            else:
                print(epoch, "_2 : ", tree_copy)
                tree_copy[direction] = 9 ## create new tree
    
    
    

0hello
1bye


In [361]:
# arr_features[]
mask = arr_features[:, 1] > 15.7
arr_features[mask]
# arr_target
for val in matrix[:, 1]:
    print(val)

0
1


In [31]:
dict_test = {'right':{'left':None}}
if dict_test['right']['left'] == None:
    dict_test['right']['left'] = {'right':None}
dict_test

{'right': {'left': {'right': None}}}

In [26]:
tree_depth = 3
matrix_test = generate_unique_combinations_matrix(tree_depth)
# matrix_test[:,1]
def branch_creator(tree, branches, tree_depth):
    for route in range(len(branches[0, :])):
        tree_copy = tree
        epoch = 0
        for branch in branches[:, route]:
            epoch +=1
            direction = ["left", "right"][branch]
            if epoch < tree_depth:
                tree_copy = tree_copy[direction]
                print(epoch,' : ' , tree_copy)
            else:
                print(epoch, "_2 : ", tree_copy)
                tree_copy[direction] = 9 ## create new tree

branch_creator(test, matrix_test, tree_depth)

1  :  {'left': {'right': 1, 'left': 1}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 1, 'left': 1}
3 _2 :  {'right': 1, 'left': 1}
1  :  {'left': {'right': 1, 'left': 9}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 1, 'left': 9}
3 _2 :  {'right': 1, 'left': 9}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 2, 'left': 2}
3 _2 :  {'right': 2, 'left': 2}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 2, 'left': 9}}
2  :  {'right': 2, 'left': 9}
3 _2 :  {'right': 2, 'left': 9}
1  :  {'left': {'right': 3, 'left': 3}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 3, 'left': 3}
3 _2 :  {'right': 3, 'left': 3}
1  :  {'left': {'right': 3, 'left': 9}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 3, 'left': 9}
3 _2 :  {'right': 3, 'left': 9}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 4, 'left': 4}
3 _2 :  {'right': 4, 'left': 4}
1  :  {'left': {'right': 9, 'left': 9}, 'right':

In [297]:
len(arr_features)

569

In [25]:
test = {
    "left": {"left": {"right": 1, "left": 1}, "right": {"right": 2, "left": 2}},
    "right": {"left": {"right": 3, "left": 3}, "right": {"right": 4, "left": 4}},
}
test['left']['left']
# matrix
matrix[:, 0]

NameError: name 'matrix' is not defined

In [384]:
test.copy()

{'left': {'left': {'right': 0}, 'right': {'right': 0}},
 'right': {'left': {'right': 0}, 'right': {'right': 0}}}

In [ ]:
# how to travel down branches...
# would just need to add the for loop and variable assignement for threshold and feature
directions = ['left', 'right']
testing = test
# for loop through matrix columns
for val in matrix[:, 0]:
    testing = testing[directions[val]]
    if testing == None:
        break
    print(testing)
matrix[:, 0]

{'left': {'right': 0}}
{'right': 0}


array([0, 0])

In [ ]:
tree_depth = 3
matrix_test = generate_unique_combinations_matrix(tree_depth)
# matrix_test[:,1]
def branch_creator(tree, branches, tree_depth):
    for route in range(len(branches[0, :])):
        tree_copy = tree
        epoch = 0
        for branch in branches[:, route]:
            epoch +=1
            direction = ["left", "right"][branch]
            if epoch < tree_depth:
                tree_copy = tree_copy[direction]
                print(epoch,' : ' , tree_copy)
            else:
                print(epoch, "_2 : ", tree_copy)
                tree_copy[direction] = 9 ## create new tree

branch_creator(test, matrix_test, tree_depth)

1  :  {'left': {'right': 1, 'left': 1}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 1, 'left': 1}
3 _2 :  {'right': 1, 'left': 1}
1  :  {'left': {'right': 1, 'left': 9}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 1, 'left': 9}
3 _2 :  {'right': 1, 'left': 9}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 2, 'left': 2}}
2  :  {'right': 2, 'left': 2}
3 _2 :  {'right': 2, 'left': 2}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 2, 'left': 9}}
2  :  {'right': 2, 'left': 9}
3 _2 :  {'right': 2, 'left': 9}
1  :  {'left': {'right': 3, 'left': 3}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 3, 'left': 3}
3 _2 :  {'right': 3, 'left': 3}
1  :  {'left': {'right': 3, 'left': 9}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 3, 'left': 9}
3 _2 :  {'right': 3, 'left': 9}
1  :  {'left': {'right': 9, 'left': 9}, 'right': {'right': 4, 'left': 4}}
2  :  {'right': 4, 'left': 4}
3 _2 :  {'right': 4, 'left': 4}
1  :  {'left': {'right': 9, 'left': 9}, 'right':

In [412]:
test

{'left': {'left': {'right': 9, 'left': 9}, 'right': {'right': 9, 'left': 9}},
 'right': {'left': {'right': 9, 'left': 9}, 'right': {'right': 9, 'left': 9}}}

In [288]:
entropy(arr_target[arr_mean_radius > test[1]],)

KeyError: 1

In [ ]:
len(arr_target[arr_mean_radius > test[1]])

0.9964850615114236

In [203]:
## information gain
parent_arr = arr_target
child_arr_1 = arr_target[arr_mean_radius > test[1]]
child_arr_2 = arr_target[arr_mean_radius < test[1]]

parent_entropy = entropy(parent_arr)
child_entropy_1 = entropy(child_arr_1)
child_entropy_2 = entropy(child_arr_2)


child_weight_1 = weights(parent_arr, child_arr_1)
child_weight_2 = 1 - child_weight_1

information_gain(
    parent_entropy, [child_entropy_1, child_entropy_2], [child_weight_1, child_weight_2]
)

np.float64(0.0023691207047248364)

In [202]:
child_entropy_1

np.float64(0.953617909992363)

In [241]:
weighted_entropy_val, feature_threshold_val, feature = find_best_split(arr_features, arr_target)
find_best_split(arr_features, arr_target)

(np.float64(0.3906482372753088), np.float64(105.95), 22)

In [364]:
build_tree(arr_features, arr_target)

{'feature': 22,
 'threshold': np.float64(105.95),
 'left': {'feature': 22,
  'threshold': np.float64(117.45),
  'left': None,
  'right': None},
 'right': {'feature': 27,
  'threshold': np.float64(0.13505),
  'left': None,
  'right': None}}

In [242]:
weighted_entropy_val

np.float64(0.3906482372753088)

In [ ]:
arr_features[:, 22] > feature_threshold_val

array([184.6 , 158.8 , 152.5 ,  98.87, 152.2 , 103.4 , 153.2 , 110.6 ,
       106.2 ,  97.65, 123.8 , 136.5 , 151.7 , 112.  , 108.8 , 124.1 ,
       123.4 , 136.8 , 186.8 ,  99.7 ,  96.09,  65.13, 125.1 , 188.  ,
       177.  , 152.4 , 122.4 , 139.9 , 149.3 , 134.9 , 160.5 , 119.4 ,
       136.1 , 161.4 , 132.7 , 133.5 , 116.2 ,  84.46,  95.54, 107.3 ,
       102.5 ,  87.22, 177.4 , 113.1 , 105.5 , 150.6 ,  57.26, 102.8 ,
        89.88,  99.  ,  82.98,  96.08,  83.67, 135.1 , 117.7 ,  81.81,
       170.1 , 115.7 ,  90.24,  59.9 ,  69.86,  62.06, 119.1 ,  65.59,
       111.8 , 114.6 ,  67.03,  78.  ,  65.5 ,  85.67, 165.9 ,  62.56,
       151.6 , 110.3 ,  89.71, 128.8 ,  91.36, 150.1 , 170.3 ,  91.88,
        84.53,  96.66, 211.7 , 141.3 ,  87.78, 152.2 , 108.4 , 152.9 ,
        91.46, 109.4 , 102.9 , 107.5 , 104.5 ,  97.59, 123.5 , 156.1 ,
        82.14,  68.81,  82.96, 109.5 , 108.6 ,  50.41,  84.58,  72.22,
        74.22, 106.4 ,  85.51,  85.56, 206.8 ,  83.99,  71.68,  89.  ,
      

In [245]:
entropy(arr_target[arr_features[:, 22] > feature_threshold_val])

np.float64(0.5559671540224538)

In [246]:
entropy(arr_target[arr_features[:, 22] < feature_threshold_val])

np.float64(0.283310737706148)

In [248]:
arr_target[arr_features[:, 22] > feature_threshold_val]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0])

In [ ]:
arr_features

0


In [227]:
arr_features[:,29]

array([0.1189 , 0.08902, 0.08758, 0.173  , 0.07678, 0.1244 , 0.08368,
       0.1151 , 0.1072 , 0.2075 , 0.08452, 0.1048 , 0.1023 , 0.06287,
       0.1431 , 0.1341 , 0.08216, 0.1142 , 0.07615, 0.07259, 0.08183,
       0.07773, 0.09946, 0.07526, 0.09564, 0.1059 , 0.1275 , 0.07421,
       0.09876, 0.07919, 0.09782, 0.1402 , 0.08482, 0.1123 , 0.1233 ,
       0.08633, 0.1014 , 0.06169, 0.05504, 0.1071 , 0.07146, 0.09606,
       0.1038 , 0.1027 , 0.09618, 0.09185, 0.07409, 0.1179 , 0.08301,
       0.06917, 0.06563, 0.08025, 0.07408, 0.07987, 0.07873, 0.07036,
       0.08294, 0.1094 , 0.06289, 0.09026, 0.0802 , 0.07712, 0.1132 ,
       0.0849 , 0.1031 , 0.08911, 0.09211, 0.06641, 0.1175 , 0.0641 ,
       0.06589, 0.1084 , 0.1339 , 0.103  , 0.07609, 0.06387, 0.07191,
       0.1108 , 0.09964, 0.07918, 0.08851, 0.1016 , 0.1051 , 0.09203,
       0.07924, 0.08579, 0.06846, 0.09288, 0.09261, 0.08473, 0.07246,
       0.06828, 0.06206, 0.06603, 0.08234, 0.08368, 0.07376, 0.08988,
       0.08756, 0.09

In [231]:
num_features = arr_features.shape[1]

In [230]:
num_features

30

In [ ]:
class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value  # For leaf nodes

In [250]:
# Example of constructing the tree
root = Node(
    feature=0,
    threshold=5.5,
    left=Node(feature=1, threshold=2.3, left=Node(value=0), right=Node(value=1)),
    right=Node(
        feature=2,
        threshold=7.8,
        left=Node(value=1),
        right=Node(feature=3, threshold=4.1, left=Node(value=0), right=Node(value=1)),
    ),
)

In [258]:
root.left.left.value

0

In [ ]:
test = {
    'feature': 0,
    'threshold': 3.5,
    'left':
    'right': }

In [262]:
def create_leaf(leaf_node,
                feature = None, 
                threshold = None, 
                class_value = None):
    if leaf_node == 0:
        leaf_dictionary = {'feature': feature,
                           'threshold': threshold,
                           'left':None,
                           'right':None }
    elif leaf_node == 1:
        leaf_dictionary = {"class": class_value}
        
    return leaf_dictionary

In [267]:
test = create_leaf(leaf_node=0, feature = 0, threshold = 2.2, class_value=1)

In [269]:
test["left"] = create_leaf(leaf_node=1, class_value=1)

In [270]:
test

{'feature': 0, 'threshold': 2.2, 'left': {'class': 1}, 'right': None}

In [301]:
# 3 x 8

In [ ]:
for x in [0, 0, 1]:
    for y in [0, 1, 0]:
        for z in [1, 0, 0]:
            np.

In [304]:
for i, j in product([0, 1], [0, 1]):
    np.array([1,j])

NameError: name 'product' is not defined

In [356]:
import itertools
import numpy as np


def generate_unique_combinations_matrix(rows):
    """
    Generate a matrix with unique combinations of 0s and 1s for each column.

    Parameters:
    rows (int): Number of rows in the matrix.

    Returns:
    np.ndarray: A binary matrix of shape (rows, 2^rows) with unique column combinations.
    """
    # Generate all possible unique combinations for the given number of rows
    all_combinations = np.array(list(itertools.product([0, 1], repeat=rows)))
    return all_combinations.T  # Transpose so that columns represent unique combinations


# Example: Generate a matrix for 3 rows
matrix = generate_unique_combinations_matrix(rows=2)
print(matrix)

[[0 0 1 1]
 [0 1 0 1]]


In [348]:
matrix[:,0]

array([0, 0, 0])

In [327]:
np.array(([1,1,0, 1, 1, 0, 0, 0])).reshape(-1,4)

array([[1, 1, 0, 1],
       [1, 0, 0, 0]])